/* interview.js — the interview question bank, classified easy / medium / hard,
   each with a model answer and a lesson link. Consumed by the #/interview view. */
window.INTERVIEW = [
  /* ---------------- EASY ---------------- */
  { d: "easy", q: "What is a qubit, and how is it different from a classical bit?", see: "qubit",
    a: "A qubit is a two-level quantum system whose state is a unit vector a|0> + b|1> with complex amplitudes. A bit is definitely 0 or 1; a qubit can be in a superposition, but a measurement still returns a single classical bit with probability |a|^2 or |b|^2." },
  { d: "easy", q: "What does measurement do to a quantum state?", see: "quantum-world",
    a: "It returns one outcome from the chosen orthonormal basis at random, with probabilities given by the Born rule (|overlap|^2), and collapses the state to that outcome. It is irreversible and destroys the superposition." },
  { d: "easy", q: "Why must every quantum gate be unitary?", see: "eigen",
    a: "Unitary maps preserve vector length, which is conservation of total probability, and they are reversible (U-inverse = U-dagger). A non-unitary 'gate' could create or destroy probability, which physics forbids." },
  { d: "easy", q: "What is the Hadamard gate used for?", see: "single-gates",
    a: "It creates equal superposition (|0> to |+>, |1> to |->), converts between the Z and X measurement bases, and is its own inverse. It is the standard 'fan-out' gate at the start of many algorithms." },
  { d: "easy", q: "What is a Bell state and how do you make one?", see: "entanglement",
    a: "A maximally entangled two-qubit state such as (|00> + |11>)/root2. You make it with a Hadamard on one qubit followed by a CNOT to the other." },
  { d: "easy", q: "Global phase vs relative phase — which matters?", see: "evolution",
    a: "Global phase (an overall factor on the whole state) is physically unobservable. Relative phase (between components of a superposition) is real, measurable information that interference reveals." },
  { d: "easy", q: "What does the 'shots' parameter control, and how does precision scale with it?", see: "sampling",
    a: "Shots is how many times the circuit is run and measured to build statistics. Precision improves only as 1/root(shots), so 10x more accuracy costs 100x more shots." },
  { d: "easy", q: "What is the Bloch sphere?", see: "bloch",
    a: "A unit sphere on which every single-qubit pure state is a point (angles theta, phi). Gates are rotations; orthogonal states sit at antipodes (180 degrees apart), and it cannot represent global phase or entangled multi-qubit states." },
  { d: "easy", q: "Distinguish T1 and T2.", see: "noise",
    a: "T1 is energy relaxation — how long a qubit stays in |1> before decaying to |0>. T2 is dephasing — how long relative-phase coherence survives, always at most 2.T1. T2 attacks the superposition information itself." },
  { d: "easy", q: "What is Qiskit and what are the V2 primitives?", see: "real-hardware",
    a: "Qiskit is IBM's Python SDK for quantum circuits. The V2 primitives are the execution interfaces: SamplerV2 returns measurement samples, EstimatorV2 returns expectation values; both take PUBs (circuit + parameters + shots/observables)." },

  /* ---------------- MEDIUM ---------------- */
  { d: "medium", q: "Walk through Deutsch-Jozsa. Where does the speedup come from — superposition, entanglement, or interference?", see: "deutsch-jozsa",
    a: "Hadamards spread amplitude over all inputs; one phase-oracle query writes f into the phases (via kickback); a final Hadamard layer interferes them so the all-zeros amplitude is a global SUM of the phases. Superposition writes globally but is unreadable alone; interference completes the speedup by computing that global property. (Honest caveat: the exponential gap is only vs deterministic-exact classical.)" },
  { d: "medium", q: "How does Grover's algorithm work, and what is its limit?", see: "grover",
    a: "It alternates two reflections (oracle + diffuser) that rotate the state by 2.theta per iteration toward the target, needing about (pi/4).root(N) iterations. The speedup is quadratic and provably optimal (BBBV); over-iterating rotates past the target and un-finds it, so you must compute the optimal stopping point." },
  { d: "medium", q: "What does Shor's algorithm actually do on the quantum computer?", see: "shor",
    a: "Only period-finding: it uses quantum phase estimation on the modular-multiplication unitary to find the period of a^x mod N. The reduction of factoring to period-finding and the extraction of factors via gcd are classical. It is a classical algorithm with one quantum subroutine." },
  { d: "medium", q: "Explain phase kickback.", see: "two-qubit-gates",
    a: "When a controlled-U acts with its target in an eigenstate |u> of U (eigenvalue e^{i.phi}), the target is unchanged but the control's |1> component picks up the phase e^{i.phi}. It converts 'querying a function' into 'writing phases' — the engine of DJ, BV, Grover, and QPE." },
  { d: "medium", q: "What is VQE and why is it NISQ-friendly while QPE is not?", see: "vqe",
    a: "VQE finds a Hamiltonian's lowest eigenvalue by minimizing an energy expectation value over a shallow parametrized ansatz, with a classical optimizer doing the heavy lifting — so quantum depth stays low. QPE needs deep coherent circuits (controlled powers + QFT) that decohere on NISQ hardware and await error correction." },
  { d: "medium", q: "Error mitigation vs error correction — what's the difference?", see: "noise",
    a: "Mitigation statistically corrects noisy RESULTS without extra qubits (readout correction, dynamical decoupling, twirling, zero-noise extrapolation) — cheap, NISQ, but it does not scale to deep circuits. Correction structurally removes errors using redundant qubits and syndromes, enabling arbitrarily deep computation, but is expensive and needs to be below threshold." },
  { d: "medium", q: "Why is the two-qubit gate count the thing to minimize?", see: "transpilation",
    a: "Two-qubit gates have 10-50x the error of single-qubit gates, so they dominate the error budget. Also, sparse device connectivity forces SWAP chains (about 3 two-qubit gates per hop) during routing, inflating the count further. Success probability falls roughly as e^{-(gates x error)}." },
  { d: "medium", q: "An 8% biased expectation value; you increase shots 100x. What happens to the bias?", see: "noise",
    a: "Essentially nothing. Shots reduce statistical variance (as 1/root n) but converge to the biased value. Systematic noise bias is immune to sample size — it needs mitigation, not more shots." },
  { d: "medium", q: "Honest take on QAOA and QML in 2026?", see: "qaoa",
    a: "Both are promising research directions with elegant mechanisms but NO demonstrated advantage over mature classical methods on useful problems. QAOA is throttled by the depth-vs-noise ceiling; QML faces data-loading costs, barren plateaus, and de-quantization. The credible stance names the mechanism and the unmet bar without hype or dismissal." },
  { d: "medium", q: "Why can't you copy a qubit, and what follows from that?", see: "entanglement",
    a: "The no-cloning theorem: unitarity preserves overlaps, forcing <psi|phi> = <psi|phi>^2, whose only solutions are 0 and 1 — so only orthogonal/classical states copy. Consequences: quantum cryptography works, CNOT copies only basis states (superpositions entangle), and error correction must protect data without duplicating it." },
  { d: "medium", q: "In Qiskit, a fresh 2-qubit circuit gets qc.x(0). What does the counts dict show, and why?", see: "tensor",
    a: "{'01': 1.0}. Qiskit is little-endian: qubit 0 is the RIGHTMOST bit of the label and the last tensor factor. Most textbooks mirror this; you probe once with a single flip and translate external strings with [::-1]." },

  /* ---------------- HARD ---------------- */
  { d: "hard", q: "How does error correction detect an error without destroying the encoded superposition?", see: "qec",
    a: "By measuring PARITY (stabilizer) operators via ancillas rather than the data. Stabilizers commute with the logical information, so they give the same result for |000>, |111>, and any superposition — revealing the error's fingerprint (the syndrome) while leaving the logical state intact. Measuring the data qubits directly would collapse it." },
  { d: "hard", q: "A continuous coherent over-rotation by a small angle epsilon hits an encoded qubit. After syndrome measurement, what happens?", see: "qec",
    a: "The measurement digitizes it: it projects the state into either 'no error' (prob about cos^2(epsilon/2)) or a 'full Pauli error' (prob about sin^2(epsilon/2)), both exactly correctable. You never correct a partial rotation — this digitization of continuous errors is why QEC is possible at all." },
  { d: "hard", q: "Explain physical vs logical qubits and translate a '1000-qubit' headline.", see: "surface-code",
    a: "A logical qubit is error-corrected and built from many physical qubits — roughly 2d^2 (hundreds to thousands) for a useful code distance d. So 1000 PHYSICAL qubits is at most a handful of logical qubits, and likely zero fully-corrected ones. Algorithm requirements are quoted in logical qubits; headlines quote physical. Divide by hundreds-to-thousands." },
  { d: "hard", q: "Why does halving a device's physical error rate shrink a fault-tolerant machine quadratically?", see: "surface-code",
    a: "Below threshold, logical error scales as (p/p_th)^(d/2), so a lower physical error p reaches the target logical error at a smaller code distance d. Since physical qubits scale as about 2d^2, a smaller d cuts the count quadratically. This is why the roadmap is fundamentally a fidelity race." },
  { d: "hard", q: "Why is the T gate the central cost driver in fault-tolerant computing?", see: "ftqc",
    a: "By Eastin-Knill no code has a transversal universal gate set. Cliffords (cheap, transversal) alone are classically simulable (Gottesman-Knill), so you need a non-Clifford gate — the T gate — which is NOT transversal and must be built from distilled magic states. T-count therefore dominates the qubit and time budget, and magic-state factories can exceed the data registers in size." },
  { d: "hard", q: "Distinguish Grover's and Shor's threats to cryptography and the right defense to each.", see: "shor",
    a: "Grover gives a QUADRATIC speedup on brute-force key search, weakening symmetric crypto — fixed by doubling the key length (AES-256). Shor gives an EXPONENTIAL break of public-key crypto (RSA, ECC) via period-finding — fixed by migrating to post-quantum (lattice-based) standards. Different threats, different responses; conflating them is a common error." },
  { d: "hard", q: "What is the honest state of quantum computing in 2026, in a sentence?", see: "ftqc",
    a: "Below-threshold error correction is demonstrated and the first small logical qubits exist, but useful fault-tolerant machines — thousands of logical qubits running billions of gates — remain an engineering marathon credibly estimated at 2029-2035+. The science is proven; the scale is years away; anyone giving a confident single date is selling something." },
  { d: "hard", q: "A vendor claims 'quantum computer solves optimization 100x faster.' What do you ask?", see: "landscape",
    a: "Beat WHAT — brute force (trivial to beat) or a mature classical solver like simulated annealing / Goemans-Williamson / a commercial optimizer? On a useful-sized instance? And did the classical side get a fair shot (or was the result later de-quantized)? As of 2026 no QAOA-style method has beaten mature classical solvers on practical problems." },
  { d: "hard", q: "You need to distinguish two outcome probabilities, 6% vs 3%, at 3 sigma. How many shots?", see: "sampling",
    a: "Use n >= 9.p(1-p)/(gap)^2. With p about 0.06, p(1-p) about 0.056, gap 0.03: n about 9 x 0.056 / 0.0009 = about 560 shots. Add headroom for plots and replication (say 1000). The reflex: shots buy precision as root(n); size the budget from the gap you must resolve." },
  { d: "hard", q: "Your VQE converges above the true ground energy even on a perfect noiseless simulator. Diagnose.", see: "vqe",
    a: "It's the ANSATZ, not noise. The variational principle guarantees energy >= E0 always, with equality only if the ground state is reachable by the ansatz. Noiseless convergence above E0 means the ansatz can't express the (entangled) ground state — add a layer or switch ansatz. Debugging rule: noiseless simulation isolates ansatz error from noise error." }
];
