/* build.js — compile lessons/<module>/<nn>-<id>.md into content/<module>.js
   and lint them (quiz JSON, fence balance, math delimiters, manifest sync).
   Usage: node tools/build.js            (from the course root)          */
"use strict";
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const LESSONS = path.join(ROOT, "lessons");
const CONTENT = path.join(ROOT, "content");

/* load manifest + diagrams with a window stub */
global.window = {};
require(path.join(CONTENT, "manifest.js"));
try { require(path.join(ROOT, "assets", "js", "diagrams.js")); } catch (e) { /* not built yet */ }
const COURSE = window.COURSE;
const DIAGRAMS = window.DIAGRAMS || {};

let problems = 0, files = 0, lessonsBuilt = 0;
const warn = (msg) => { console.log("  ⚠ " + msg); problems++; };

function lint(md, label) {
  /* quiz blocks parse as JSON */
  const quizRe = /^```quiz[ \t]*\n([\s\S]*?)\n```[ \t]*$/gm;
  let m, quizzes = 0;
  while ((m = quizRe.exec(md))) {
    quizzes++;
    try {
      const q = JSON.parse(m[1]);
      if (!q.q || !Array.isArray(q.options) || typeof q.answer !== "number" || !q.why)
        warn(`${label}: quiz missing fields (q/options/answer/why)`);
      else if (q.answer < 0 || q.answer >= q.options.length)
        warn(`${label}: quiz answer index out of range`);
    } catch (e) { warn(`${label}: quiz JSON invalid — ${e.message}`); }
  }
  /* solution fences balanced (every ````solution has a closing ````) */
  const opens = (md.match(/^````solution[ \t]*$/gm) || []).length;
  const fences4 = (md.match(/^````/gm) || []).length;
  if (fences4 !== opens * 2) warn(`${label}: unbalanced \`\`\`\` solution fences (${opens} opens, ${fences4} total marks)`);
  /* display math balanced */
  const dd = (md.match(/\$\$/g) || []).length;
  if (dd % 2) warn(`${label}: odd number of $$ delimiters`);
  /* single-$ parity outside code fences (heuristic) */
  const noCode = md
    .replace(/^````solution[ \t]*\n[\s\S]*?\n````[ \t]*$/gm, "")
    .replace(/^```[\w+-]*[ \t]*\n[\s\S]*?\n```[ \t]*$/gm, "")
    .replace(/`[^`\n]*`/g, "")
    .replace(/\$\$[\s\S]*?\$\$/g, "");
  const singles = (noCode.match(/\$/g) || []).length;
  if (singles % 2) warn(`${label}: odd number of single $ delimiters (math will break)`);
  /* diagram keys exist */
  const dRe = /^@@diagram:([\w-]+)/gm;
  while ((m = dRe.exec(md))) {
    if (!DIAGRAMS[m[1]]) warn(`${label}: diagram key "${m[1]}" not found in diagrams.js`);
  }
  return { quizzes };
}

console.log("Building course content…\n");
for (const mod of COURSE.modules) {
  const dir = path.join(LESSONS, mod.id);
  const out = {};
  const found = new Set();
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir).sort()) {
      if (!f.endsWith(".md")) continue;
      files++;
      const id = f.replace(/^\d+-/, "").replace(/\.md$/, "");
      const md = fs.readFileSync(path.join(dir, f), "utf8");
      if (!mod.lessons.some((l) => l.id === id)) {
        warn(`${mod.id}/${f}: no lesson "${id}" in manifest`);
        continue;
      }
      lint(md, `${mod.id}/${f}`);
      out[id] = md;
      found.add(id);
      lessonsBuilt++;
    }
  }
  for (const l of mod.lessons)
    if (!found.has(l.id)) warn(`${mod.id}: lesson "${l.id}" has no .md file yet`);

  const js =
    "/* generated by tools/build.js — do not edit; edit lessons/" + mod.id + "/*.md */\n" +
    "window.CONTENT = Object.assign(window.CONTENT || {}, " +
    JSON.stringify(out, null, 0) + ");\n";
  fs.writeFileSync(path.join(CONTENT, mod.id + ".js"), js);
  console.log(`  ${mod.id}: ${Object.keys(out).length}/${mod.lessons.length} lessons → content/${mod.id}.js`);
}
console.log(`\n${lessonsBuilt} lessons compiled from ${files} files. ` +
  (problems ? `${problems} warning(s) — fix before shipping.` : "No problems found. ✅"));
process.exit(0);
